name: User Onboarding
description: Onboard users to repositories and organizations
title: "[Onboarding]: "
labels: ["onboarding"]
body:
  - type: markdown
    attributes:
      value: |
        Use this template to onboard users to repositories and organizations.
        
        After creating the issue, add a comment with the onboarding commands.
        
        For repositories:
        /onboard repos
        username1,owner/repo1,permission
        username2,owner/repo2,permission
        /end
        
        For organizations:
        /onboard orgs
        username1,org1,role
        username2,org2,role
        /end
        
        Permissions for repos: pull, push, admin
        Roles for orgs: admin, direct_member, billing_manager
  - type: input
    id: requester
    attributes:
      label: Requester
      description: Who is requesting this onboarding?
      placeholder: @username
    validations:
      required: true