name: IssueOps

on:
  issue_comment:
    types: [created]

jobs:
  process-command:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/issueops')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run add_repo script
      if: contains(github.event.comment.body, '/issueops add_repo')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: python scripts/add_repo.py

    - name: Run add script
      if: contains(github.event.comment.body, '/issueops add')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: python scripts/add.py