name: IssueOps

on:
  issue_comment:
    types: [created]

jobs:
  process-command:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/issueops')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Debug - Environment and File System
      run: |
        echo "Current working directory:"
        pwd
        echo "Contents of current directory:"
        ls -la
        echo "Contents of scripts directory:"
        ls -la scripts/
        echo "Installed Python packages:"
        pip list
        echo "Python version:"
        python --version

    - name: Run add_repo script
      if: contains(github.event.comment.body, '/issueops add_repo')
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: |
        echo "Running add_repo script"
        python -m pip install python-dotenv  # Install python-dotenv
        python scripts/add_repo.py
        if [ $? -ne 0 ]; then
          echo "Error: add_repo script failed"
          exit 1
        fi

    - name: Run add script
      if: contains(github.event.comment.body, '/issueops add')
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: |
        echo "Running add script"
        python -m pip install python-dotenv  # Install python-dotenv
        python scripts/add.py
        if [ $? -ne 0 ]; then
          echo "Error: add script failed"
          exit 1
        fi

    - name: Error handling
      if: failure()
      run: |
        echo "An error occurred during the workflow execution"
        echo "Please check the logs above for more details"