name: IssueOps

on:
  issue_comment:
    types: [created]

jobs:
  process-command:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/issueops')
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-dotenv

    - name: Debug - Environment and File System
      run: |
        echo "Current working directory:"
        pwd
        echo "Contents of current directory:"
        ls -la
        echo "Contents of scripts directory:"
        ls -la scripts/
        echo "Environment variables:"
        env
        echo "GitHub workspace:"
        echo ${{ github.workspace }}

    - name: Run add_repo script
      if: contains(github.event.comment.body, '/issueops add_repo')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INVITATIONS_CSV_PATH: ${{ github.workspace }}/data/invitations.csv
      run: |
        echo "INVITATIONS_CSV_PATH: $INVITATIONS_CSV_PATH"
        if [ -f "$INVITATIONS_CSV_PATH" ]; then
          echo "invitations.csv found, running script"
          python scripts/add_repo.py
        else
          echo "Error: invitations.csv not found at $INVITATIONS_CSV_PATH"
          ls -la $(dirname "$INVITATIONS_CSV_PATH")
          exit 1
        fi

    - name: Run add script
      if: contains(github.event.comment.body, '/issueops add')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COLLABORATORS_CSV_PATH: ${{ github.workspace }}/data/collaborator.csv
      run: |
        echo "COLLABORATORS_CSV_PATH: $COLLABORATORS_CSV_PATH"
        if [ -f "$COLLABORATORS_CSV_PATH" ]; then
          echo "collaborator.csv found, running script"
          python scripts/add.py
        else
          echo "Error: collaborator.csv not found at $COLLABORATORS_CSV_PATH"
          ls -la $(dirname "$COLLABORATORS_CSV_PATH")
          exit 1
        fi