name: User Onboarding Automation

on:
  issue_comment:
    types: [created]

jobs:
  process_command:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '/onboard')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Process organization additions
      if: contains(github.event.comment.body, '/onboard orgs')
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: |
        USERS_DATA=$(echo "$COMMENT_BODY" | sed -n '/\/onboard orgs/,/\/end/p' | sed '1d;$d')
        python scripts/add_to_orgs.py "$USERS_DATA"
      continue-on-error: true

    - name: Process repository additions
      if: contains(github.event.comment.body, '/onboard repos')
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        COMMENT_BODY: ${{ github.event.comment.body }}
      run: |
        USERS_DATA=$(echo "$COMMENT_BODY" | sed -n '/\/onboard repos/,/\/end/p' | sed '1d;$d')
        python scripts/add_to_repos.py "$USERS_DATA"
      continue-on-error: true

    - name: Check for failures
      if: failure()
      run: |
        echo "One or more onboarding processes failed. Please check the logs for details."
        exit 1